name: Deploy MultiDocker App
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
      - run: docker build -t kaness-it/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true kaness-it/react-test npm test
 
      - run: docker build -t kaness-it/multi-client-10-14 ./client
      - run: docker build -t kaness-it/multi-nginx-10-14 ./nginx
      - run: docker build -t kaness-it/multi-server-10-14 ./server
      - run: docker build -t kaness-it/multi-worker-10-14 ./worker
 
      - run: docker push kaness-it/multi-client-10-14
      - run: docker push kaness-it/multi-nginx-10-14
      - run: docker push kaness-it/multi-server-10-14
      - run: docker push kaness-it/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: complex-app
          environment_name: Complexapp-env
          existing_bucket_name: elasticbeanstalk-eu-west-1-501669463782
          region: eu-west-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip